Updated delta bash script

diff --git a/deliverable/script b/deliverable/script
--- a/deliverable/script
+++ b/deliverable/script
@@ -1,20 +1,28 @@
 #!/bin/bash
 
-# Set Test, Command, and Timeout variables
-TEST_FILE=$1
-COMMAND=/home/vboxuser/Documents/fuzzing/mysort		
-TIMEOUT=4
+echo $(pwd)
+
+# Set Variables
+TEST_FILE="$1"
+FULL_PATH=$(realpath "$1")
+COMMAND=$(realpath "/home/vboxuser/Documents/fuzzing/mysort")		
+TIMEOUT=2
 
 # Print Vars
-echo "Testing File: $TEST_FILE"
+echo "Testing File: $FULL_PATH"
 echo "Running Command: $COMMAND"
 echo "Timeout Value: $TIMEOUT"
+
+OUTPUT=$("$COMMAND" "$FULL_PATH" "$TIMEOUT" 2>&1)
+
+echo "$OUTPUT"
 
 # Run the sort command and check for timeout
 # Returns 0 for no error
 # Returns 1 for no error
-if echo $("COMMAND" "$TEST_FILE" "$TIMEOUT" 2>&1) | grep -q "Error: timeout"; then
-    exit 1
-else
-    exit 0
+if echo "$OUTPUT" | grep -q "Error: timeout"; then
+    echo "HANG"
+    exit 0;
 fi
+echo "NO HANG"
+exit 1;
